package com.minispl.application.playbook;

import com.minispl.domain.enums.PlaybookPhase;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

/**
 * Report generated by the Template Method execution of an InvestigationEngine.
 * Records the results and timestamps of all 5 enforced phases:
 * Triage -> Containment -> Evidence Collection -> Eradication -> Post-Mortem.
 */
public class InvestigationReport {

    private final int incidentId;
    private final String threatType;
    private final List<InvestigationStepResult> stepResults = new ArrayList<>();
    private final LocalDateTime startTime;
    private LocalDateTime completionTime;
    private boolean fullyCompleted;

    public InvestigationReport(int incidentId, String threatType) {
        this.incidentId = incidentId;
        this.threatType = threatType;
        this.startTime = LocalDateTime.now();
        this.fullyCompleted = false;
    }

    public void addStepResult(InvestigationStepResult result) {
        if (result != null) {
            stepResults.add(result);
        }
    }

    public void markCompleted() {
        this.completionTime = LocalDateTime.now();
        this.fullyCompleted = stepResults.size() >= 5 && stepResults.stream().allMatch(InvestigationStepResult::isSuccess);
    }

    public int getIncidentId() {
        return incidentId;
    }

    public String getThreatType() {
        return threatType;
    }

    public List<InvestigationStepResult> getStepResults() {
        return Collections.unmodifiableList(stepResults);
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public LocalDateTime getCompletionTime() {
        return completionTime;
    }

    public boolean isFullyCompleted() {
        return fullyCompleted;
    }

    public boolean isAllSuccessful() {
        return !stepResults.isEmpty() && stepResults.stream().allMatch(InvestigationStepResult::isSuccess);
    }

    public Optional<InvestigationStepResult> getResultForPhase(PlaybookPhase phase) {
        return stepResults.stream()
                .filter(r -> r.getPhase() == phase)
                .findFirst();
    }

    public String getExecutionSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("=== DFIR Investigation Report for Case #%d [%s] ===\n", incidentId, threatType));
        sb.append(String.format("Started: %s | Completed: %s | Status: %s\n",
                startTime, completionTime != null ? completionTime : "IN_PROGRESS",
                fullyCompleted ? "ALL_PHASES_PASSED" : "FAILED_OR_INCOMPLETE"));
        sb.append("Phase Results:\n");
        for (InvestigationStepResult r : stepResults) {
            sb.append(String.format("  [%s] %s: %s (Action: %s)\n",
                    r.getPhase(), r.getStepName(), r.isSuccess() ? "PASSED" : "FAILED", r.getActionTaken()));
        }
        return sb.toString();
    }
}
